apiVersion: "database.camilocot/v1alpha1"
kind: "Cassandra"
metadata:
  name: "cassandra-cluster"
spec:
  size: 2
  version: v13
  partition: 1
  storageClassName: local-storage
  cassandraEnv:
  - name: MAX_HEAP_SIZE
    value: "410M"
  - name: "CASSANDRA_CLUSTER_NAME"
    value: "Test"
